[build]
  # This will be run the site build
  command = "nodemon --experimental-modules server.js"
  # This is the directory is publishing to netlify's CDN
  publish = "dist"
  # functions build directory
  functions = "functions-build"
